import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import TabProvider from "@/context/tabContext";
import UserProvider from "@/context/userContext";
// import { Navbar, Nav } from 'react-bootstrap';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "iTube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className} bg-my-bg`}>
        <UserProvider>
          <TabProvider>
              <main className="z-5">
                {children}
              </main>
              <Toaster position="top-center" richColors />
          </TabProvider>
        </UserProvider>
      </body>
    </html>
  );
}
